# Generated by Django 4.2 on 2023-04-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('market_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='market_data_source',
            field=models.CharField(
                choices=[('binance', 'Binance'), ('kraken', 'Kraken'), ('bybit', 'Bybit')], max_length=255
            ),
        ),
        migrations.AddConstraint(
            model_name='ohlc',
            constraint=models.UniqueConstraint(fields=('instrument', 'start_time', 'end_time'), name='unique_ohlc'),
        ),
    ]
