[project]
name = "django-soyba"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "binance-connector>=2.0.0",
    "celery>=5.4.0",
    "django>=4.2.16",
    "django-celery>=3.1.17",
    "djangorestframework>=3.15.2",
    "gunicorn>=23.0.0",
    "psycopg2-binary>=2.9.10",
    "redis>=5.2.0",
    "pybit>=5.8.0",
    "typer>=0.12.5",
]

[tool.pytest.ini_options]
python_files = "tests.py test_*.py *_tests.py"
norecursedirs = "*.egg .eggs dist build docs .tox .git __pycache__ load_testing"
filterwarnings= [
    "ignore::DeprecationWarning"
]
addopts = "-v -s"

[tool.black]
line-length = 120
skip-string-normalization = true
target-version = ['py311']

[tool.isort]
profile = "black"
line_length = 120

[tool.ruff]
target-version = 'py311'
line-length = 120
indent-width = 4

[tool.ruff.lint]
select = ['ALL']
ignore = [
  'ANN001',
  'ANN101',
  'ANN201',
  'ANN202',
  'ANN204',

  'ARG001',
  'ARG002',

  'A002',
  'A003',

  'B008',

  'C408',

  'D100',
  'D101',
  'D102',
  'D103',
  'D104',
  'D105',
  'D107',
  'D203',
  'D212',
  'D213',

  'E402',

  'FA102',

  'G004',

  'I001',

  'N806',

  'PLR0913',

  'Q000',

  'S106',
  'S311',
]

[tool.ruff.lint.per-file-ignores]
'src/tests/*' = [
  'S101',
  'S105',
  'S106',
  'S107',
  'S311',
]
'dockerfiles/*' = [
  'S603',
]

'alembic/**/*' = [
  'D400',
  'D415',

  'INP001',
]

[tool.pyright]
include = ["src"]
pythonVersion = "3.11"
pythonPlatform = "Linux"

[dependency-groups]
dev = [
    "black>=24.10.0",
    "hypothesis[django]>=6.115.5",
    "pytest>=8.3.3",
    "pytest-mock>=3.14.0",
    "ruff>=0.7.1",
    "django-stubs>=5.1.1",
    "djangorestframework-stubs>=3.15.1",
]
