#!/bin/env python
import subprocess

from typer import Typer

typer = Typer()


def sh(command: str):
    return subprocess.run(command.split(), check=True)


@typer.command()
def build():
    sh("docker compose build --no-cache")


@typer.command()
def up():
    sh("docker compose up -d")


@typer.command()
def down():
    sh("docker compose down")


@typer.command()
def format():
    sh("black .")


@typer.command()
def test():
    sh("pytest src/tests")


@typer.command()
def logs():
    sh("docker compose logs")


typer()
